"""AQI chart explainability metadata."""

from __future__ import annotations

from bangalore_intelligence.explainability.models import ExplainabilityEntry

AQI_EXPLAINABILITY: tuple[ExplainabilityEntry, ...] = (
    ExplainabilityEntry(
        surface_id="A-01",
        dashboard="aqi",
        surface_type="chart",
        title="PM2.5 Burden and Category Mix",
        complexity_level="basic",
        priority="high",
        what_this_shows="Current PM2.5 burden, category mix, peak context, and WHO guideline comparison.",
        why_this_visualization="A category bar view links numerical PM2.5 burden to severity composition.",
        when_to_use="Use this first to understand the overall air-quality burden in the active scope.",
        decision_relevance="High mean PM2.5 or severe category share can signal persistent public-health exposure.",
        misinterpretation_warning="Category mix summarizes severity; it does not identify the meteorological cause.",
        related_visuals=("A-05", "A-02", "A-03"),
        limitations=(
            "PM2.5 categories are derived from the active data scope.",
            "Averages can hide short severe episodes.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-02",
        dashboard="aqi",
        surface_type="chart",
        title="Weekly PM2.5 Calendar",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Weekly PM2.5 intensity across years.",
        why_this_visualization="A calendar heatmap preserves time ordering while exposing persistent polluted weeks.",
        when_to_use="Use this chart to locate high-PM2.5 weeks and seasonal blocks.",
        decision_relevance="Recurring intense weeks can guide seasonal monitoring and public-health communication.",
        misinterpretation_warning="A dark week shows elevated PM2.5, not the cause of the episode.",
        related_visuals=("A-05", "A-04", "A-01"),
        limitations=(
            "Weekly aggregation can hide day-level spikes.",
            "Selected weeks should be interpreted with seasonal context.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-03",
        dashboard="aqi",
        surface_type="chart",
        title="Seasonal PM2.5 Ridgeline",
        complexity_level="intermediate",
        priority="medium",
        what_this_shows="Distribution shape of daily PM2.5 by season.",
        why_this_visualization="Ridgelines reveal shifts, tails, and relief periods better than seasonal means alone.",
        when_to_use="Use this chart to compare winter accumulation, monsoon relief, and seasonal tail risk.",
        decision_relevance="Right-shifted or heavy-tailed seasons indicate recurring exposure risk windows.",
        misinterpretation_warning="A seasonal distribution shows pattern differences, not proof of seasonal causality.",
        related_visuals=("A-04", "A-05", "A-01"),
        limitations=(
            "Distribution estimates are less stable with fewer seasonal records.",
            "Extreme tails should be checked against daily or rolling views.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-04",
        dashboard="aqi",
        surface_type="chart",
        title="Monthly PM2.5 Heatmap",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Mean PM2.5 by month and year.",
        why_this_visualization="A month-year heatmap exposes seasonal cycles and multi-year pollution clusters.",
        when_to_use="Use this chart to identify recurring monthly PM2.5 hotspots.",
        decision_relevance="Repeated dark month-year cells can guide seasonal preparedness and monitoring.",
        misinterpretation_warning="Monthly intensity does not explain which weather or emissions factor caused pollution.",
        related_visuals=("A-02", "A-03", "A-14"),
        limitations=(
            "Monthly means can smooth over acute daily episodes.",
            "Sparse months may be less stable.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-05",
        dashboard="aqi",
        surface_type="chart",
        title="Pollution Persistence Series",
        complexity_level="basic",
        priority="high",
        what_this_shows="Daily PM2.5 values alongside a 7-day rolling mean.",
        why_this_visualization="A rolling line separates sustained pollution persistence from isolated daily spikes.",
        when_to_use="Use this chart to distinguish acute events from multi-day exposure episodes.",
        decision_relevance="Sustained elevated rolling means can indicate public-health response windows.",
        misinterpretation_warning="The rolling mean smooths daily extremes; it should be read with the raw daily values.",
        related_visuals=("A-01", "A-02", "A-06"),
        limitations=(
            "Rolling windows lag sudden changes.",
            "Missing or sparse daily records can affect continuity.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-06",
        dashboard="aqi",
        surface_type="chart",
        title="Pressure and Visibility PM2.5 Density",
        complexity_level="intermediate",
        priority="high",
        what_this_shows="PM2.5 intensity across combinations of sea-level pressure and visibility conditions.",
        why_this_visualization="A density heatmap helps reveal where atmospheric conditions and pollution burden cluster together.",
        when_to_use="Use this chart to inspect whether low visibility and pressure regimes align with elevated PM2.5.",
        decision_relevance=(
            "Repeated high-PM2.5 density under low-visibility conditions may signal recurring public-health exposure windows."
        ),
        misinterpretation_warning="Pressure and visibility associations do not prove that either variable alone caused PM2.5 changes.",
        related_visuals=("A-13", "A-14", "A-07"),
        limitations=(
            "Density cells summarize grouped conditions and can hide individual-day outliers.",
            "Atmospheric relationships are descriptive and should not be treated as causal proof.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-07",
        dashboard="aqi",
        surface_type="chart",
        title="PM2.5 Category Weather Profile",
        complexity_level="intermediate",
        priority="medium",
        what_this_shows="Normalized weather profiles across PM2.5 severity categories.",
        why_this_visualization="A radar chart makes multi-variable atmospheric signatures comparable across categories.",
        when_to_use="Use this chart to compare which weather dimensions differ between PM2.5 categories.",
        decision_relevance="Category profiles can guide which atmospheric factors deserve closer review.",
        misinterpretation_warning="Radar shape is descriptive and normalized; it is not a predictive severity model.",
        related_visuals=("A-06", "A-13", "A-15"),
        limitations=(
            "Normalization hides original units.",
            "Radar comparisons become harder with many overlapping categories.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-08",
        dashboard="aqi",
        surface_type="chart",
        title="Minimum Temperature vs PM2.5",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Relationship between minimum temperature, PM2.5, and PM2.5 category.",
        why_this_visualization="A scatter plot supports direct inspection of temperature-pollution association.",
        when_to_use="Use this chart to check whether lower temperatures align with higher PM2.5 categories.",
        decision_relevance="Temperature-linked patterns can guide seasonal and atmospheric follow-up analysis.",
        misinterpretation_warning="Temperature association does not prove temperature caused PM2.5 changes.",
        related_visuals=("A-15", "A-12", "A-03"),
        limitations=(
            "Large scopes may be sampled for readability.",
            "Scatter patterns can be confounded by season and weather regimes.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-09",
        dashboard="aqi",
        surface_type="chart",
        title="Pressure Band PM2.5 Comparison",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Mean PM2.5 across pressure bands and seasons.",
        why_this_visualization="Grouped bars make pressure-band and season comparisons easy to scan.",
        when_to_use="Use this chart to compare whether pressure regimes align with different PM2.5 levels by season.",
        decision_relevance="Pressure-band differences can focus atmospheric analysis on recurring high-burden regimes.",
        misinterpretation_warning="Pressure bands show association, not standalone causality.",
        related_visuals=("A-14", "A-06", "A-13"),
        limitations=(
            "Pressure bands simplify a continuous atmospheric variable.",
            "Small season-band groups can be less stable.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-10",
        dashboard="aqi",
        surface_type="chart",
        title="Wind Speed Band Comparison",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Mean PM2.5 across wind-speed bands and seasons.",
        why_this_visualization="Grouped bars compare dispersion-related categories without implying time sequence.",
        when_to_use="Use this chart to inspect whether stronger wind bands align with lower PM2.5.",
        decision_relevance="Wind-band differences can support investigation of pollutant dispersion conditions.",
        misinterpretation_warning="Lower PM2.5 under stronger wind does not prove wind alone reduced pollution.",
        related_visuals=("A-11", "A-06", "A-15"),
        limitations=(
            "Wind bands simplify continuous wind behavior.",
            "Season and other weather variables may confound the pattern.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-11",
        dashboard="aqi",
        surface_type="chart",
        title="Gust Ratio Quintile Check",
        complexity_level="intermediate",
        priority="medium",
        what_this_shows="Mean PM2.5 across gust-ratio quintiles with uncertainty context.",
        why_this_visualization="Quintile bars make monotonic or unstable gust-ratio relationships visible.",
        when_to_use="Use this chart to check whether gustiness aligns with PM2.5 shifts.",
        decision_relevance="A stable pattern can suggest ventilation or turbulence conditions worth deeper analysis.",
        misinterpretation_warning="Gust-ratio patterns are relationship checks, not causal proof.",
        related_visuals=("A-10", "A-15", "A-06"),
        limitations=(
            "Wide uncertainty bands reduce confidence in category differences.",
            "Quintiles simplify complex wind behavior.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-12",
        dashboard="aqi",
        surface_type="chart",
        title="Temperature Spread Bands",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Mean PM2.5 across diurnal temperature-spread bands.",
        why_this_visualization="Band bars simplify day-night temperature spread into readable comparison groups.",
        when_to_use="Use this chart to inspect whether temperature stability aligns with PM2.5 differences.",
        decision_relevance="Spread-band differences can guide follow-up analysis of atmospheric stability.",
        misinterpretation_warning="Temperature spread association does not prove atmospheric stability caused pollution.",
        related_visuals=("A-08", "A-15", "A-03"),
        limitations=(
            "Spread bands simplify a continuous variable.",
            "Seasonal effects can influence spread and PM2.5 together.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-13",
        dashboard="aqi",
        surface_type="chart",
        title="Rule-Based Atmospheric Regimes",
        complexity_level="advanced",
        priority="high",
        what_this_shows="PM2.5 behavior grouped by interpretable rule-based atmospheric regimes.",
        why_this_visualization="A regime scatter makes condition groups visible while preserving record-level variation.",
        when_to_use="Use this chart to compare baseline, low-visibility, dispersive, and pressure-regime patterns.",
        decision_relevance="Regime clusters help analysts identify recurring atmospheric contexts associated with pollution burden.",
        misinterpretation_warning="Regime labels are rule-based descriptive groups, not machine-learning predictions or causal classes.",
        related_visuals=("A-06", "A-14", "A-15"),
        limitations=(
            "Rule thresholds simplify atmospheric behavior and may not capture every meteorological nuance.",
            "Small regime groups can make comparisons less stable.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-14",
        dashboard="aqi",
        surface_type="chart",
        title="Season x Pressure Grid",
        complexity_level="basic",
        priority="medium",
        what_this_shows="Mean PM2.5 by season and sea-level pressure band.",
        why_this_visualization="A heatmap efficiently compares two categorical dimensions against pollution burden.",
        when_to_use="Use this chart to identify combined seasonal and pressure conditions associated with high PM2.5.",
        decision_relevance="Persistent hot cells can guide seasonal pressure-regime monitoring.",
        misinterpretation_warning="A dark cell shows association in the current data, not a full causal explanation.",
        related_visuals=("A-09", "A-06", "A-13"),
        limitations=(
            "Category grids can hide day-level outliers.",
            "Sparse season-pressure combinations can be less stable.",
        ),
    ),
    ExplainabilityEntry(
        surface_id="A-15",
        dashboard="aqi",
        surface_type="chart",
        title="Weather Variable Pairplot",
        complexity_level="advanced",
        priority="high",
        what_this_shows="Pairwise relationships among weather variables and PM2.5, with distribution views.",
        why_this_visualization=(
            "A pairplot supports exploratory multivariate analysis by showing many pairwise comparisons in one matrix."
        ),
        when_to_use="Use this chart when deciding which weather-PM2.5 relationships deserve deeper analysis.",
        decision_relevance=(
            "The pairplot helps analysts find candidate relationships to investigate before making operational or "
            "environmental claims."
        ),
        misinterpretation_warning="Pairwise patterns and correlations are exploratory; they do not establish causality.",
        related_visuals=("A-06", "A-08", "A-13"),
        limitations=(
            "Large datasets may be sampled for readability.",
            "Low row counts may fall back to a correlation-style summary with less visual detail.",
            "Pairwise views can miss seasonal confounding and nonlinear effects.",
        ),
    ),
)
