"""Vertical rhythm and chart-adjacent spacing tokens — single source for UI layout."""

# Section hierarchy (px)
SECTION_GAP_LG = 40
SECTION_GAP_MD = 28
SECTION_GAP_SM = 20
HERO_PADDING_Y = 28
HERO_PADDING_X = 28
HERO_TITLE_GAP = 14
HERO_IDENTITY_BOTTOM = 10
HERO_BADGE_GAP = 12

# KPI strip
KPI_CARD_MIN_HEIGHT = 132
KPI_LABEL_TO_VALUE = 10
KPI_VALUE_LINE_HEIGHT = 1.12
KPI_STRIP_COLUMN_GAP = 12
KPI_STRIP_BOTTOM = 20
KPI_STRIP_AFTER_SECONDARY = 12

# Chart shell rhythm
CHART_TITLE_TO_PLOT = 20
CHART_CAPTION_TOP = 14
CHART_FILTER_GAP = 24
CHART_SHELL_PADDING_HERO = 28
CHART_SHELL_PADDING_SUPPORT = 22
CHART_HEADER_GAP = 10
CHART_HEADER_TO_CONTROLS = 14
CHART_CONTROLS_TO_PLOT = 18
CHART_MODULE_BOTTOM = 20
CHART_FOOTER_TOP = 12
EXPANDER_CONTENT_GAP = 18
INSIGHT_BODY_TOP = 12
SECTION_HEADER_SUBTITLE_GAP = 10
SECTION_HEADER_ZONE_GAP = 8

# Plotly annotation offsets (paper coords)
ANNOTATION_TITLE_OFFSET = 0.1
ANNOTATION_CALLOUT_PAD = 10
